export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'
export const ADD_ALL_PRODUCTS = 'ADD_ALL_PRODUCTS'
export const SHOW_ALL_PRODUCTS = 'SHOW_ALL_PRODUCTS'
export const ADD_FAVORITES = 'ADD_FAVORITES'